# Generated by Django 4.2 on 2023-05-01 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppTrading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='portefeuille',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AppTrading.portefeuille'),
            preserve_default=False,
        ),
    ]
