# Generated by Django 4.2 on 2023-05-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTrading', '0002_action_portefeuille'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='buy',
            field=models.CharField(default='buy', max_length=255),
            preserve_default=False,
        ),
    ]
