# Generated by Django 4.2 on 2023-05-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTrading', '0003_action_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='titre',
            name='difference',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
